clientOptions:
  cli:
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli
        name: core
    - gcpPluginRepository:
        bucketName: tanzu-cli-tkg-plugins
        name: tkg
metadata:
  creationTimestamp: null
