clientOptions:
  cli:
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli
        name: core
    - gcpPluginRepository:
        bucketName: tanzu-cli-tkg-plugins
        name: tkg
current: arcas-mgmt
metadata:
  creationTimestamp: null
servers:
- managementClusterOpts:
    context: arcas-mgmt-admin@arcas-mgmt
    path: /root/.kube-tkg/config
  name: arcas-mgmt
  type: managementcluster
